/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Belvo from "../../../..";

export interface RetrieveTaxRetentionsRequest {
    omit?: string;
    fields?: string;
    body: Belvo.TaxRetentionsRequest;
}
