/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BelvoApi from "../../../..";

export interface RetrieveTransactionsAsyncRequest {
    omit?: string;
    fields?: string;
    body: BelvoApi.TransactionsRequest;
}
