/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as BelvoApi from "../../api";
import * as core from "../../core";

export const ForbiddenError: core.serialization.Schema<
    serializers.ForbiddenError.Raw,
    BelvoApi.AccessToResourceDenied[]
> = core.serialization.list(core.serialization.lazyObject(async () => (await import("..")).AccessToResourceDenied));

export declare namespace ForbiddenError {
    type Raw = serializers.AccessToResourceDenied.Raw[];
}
