/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Belvo from "../../api";
import * as core from "../../core";

export const UnauthorizedError: core.serialization.Schema<
    serializers.UnauthorizedError.Raw,
    Belvo.UnauthorizedErrorBody[]
> = core.serialization.list(core.serialization.lazyObject(async () => (await import("..")).UnauthorizedErrorBody));

export declare namespace UnauthorizedError {
    type Raw = serializers.UnauthorizedErrorBody.Raw[];
}
