/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../errors";
import * as BelvoApi from "..";

export class ForbiddenError extends errors.BelvoApiError {
    constructor(body: BelvoApi.AccessToResourceDenied[]) {
        super({
            message: "ForbiddenError",
            statusCode: 403,
            body: body,
        });
        Object.setPrototypeOf(this, ForbiddenError.prototype);
    }
}
