/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Belvo from "../../../..";

export interface PatchOwnersRequest {
    omit?: string;
    fields?: string;
    /**
     * A JSON object containing a session UUID and a MFA token
     */
    body: Belvo.PatchBody;
}
