/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ListTaxReturnsRequest {
    page?: number;
    pageSize?: number;
    omit?: string;
    fields?: string;
    link?: string;
    createdAtGt?: string;
    createdAtGte?: string;
    createdAtLt?: string;
    createdAtLte?: string;
    createdAtRange?: string;
    id?: string;
    idIn?: string;
    ejercicio?: string;
    ejercicioLt?: string;
    ejercicioLte?: string;
    ejercicioGt?: string;
    ejercicioGte?: string;
    ejercicioRange?: string;
    tipoDeclaracion?: string;
    tipoDeclaracionIn?: string;
    linkIn?: string;
}
