/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ListTaxDeclarationsRequest {
    page?: number;
    pageSize?: number;
    omit?: string;
    fields?: string;
    link?: string;
    linkIn?: string;
    createdAtGt?: string;
    createdAtGte?: string;
    createdAtLt?: string;
    createdAtLte?: string;
    createdAtRange?: string;
    id?: string;
    idIn?: string;
    year?: string;
    yearGt?: string;
    yearGte?: string;
    yearLt?: string;
    yearLte?: string;
    yearRange?: string;
}
