/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ListPaymentInstitutionsRequest {
    page?: number;
    country?: string;
    countryIn?: string;
    createdAt?: string;
    createdAtGt?: string;
    createdAtGte?: string;
    createdAtLt?: string;
    createdAtLte?: string;
    createdAtRange?: string;
}
