/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Belvo from "../../../..";

export interface RetrieveRiskInsightsRequest {
    omit?: string;
    fields?: string;
    body: Belvo.StandardRequest;
}
