/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BelvoApi from "../../../..";

export interface RetrieveRiskInsightsRequest {
    omit?: string;
    fields?: string;
    body: BelvoApi.StandardRequest;
}
