/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Belvo from "..";

/**
 * Breakdown of the fees applied to the loan.
 */
export interface AccountsLoanDataFees {
    type: Belvo.EnumLoanDataFeeType;
    /**
     * The total value of the fee. Same currency of the Loan.
     *
     */
    value: number;
}
