/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BelvoApi from "..";

export interface AccountsLoanDataFees {
    type: BelvoApi.EnumLoanDataFeeType;
    /**
     * The total value of the fee. Same currency of the Loan.
     *
     */
    value: number;
}
