/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Belvo from "..";

/**
 * Object containing the reported annual incomes, deductions, and final balances of the tax payer.
 */
export interface AnnualIncomeStatementIndividual {
    grossIncome: Belvo.GrossIncomeIndividual;
    nonTaxableIncome: Belvo.NonTaxableIncomeIndividual;
    netIncome: Belvo.NetIncomeIndividual;
    annualTotals: Belvo.AnnualTotalsIndividual;
}
