/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AsynchronousAccepted202 {
    /** The unique ID for this request. We recommend you store this value to later identify which webhook event relates to an asynchronous request. */
    requestId?: string;
}
