/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BelvoApi from "..";

export interface BankAccountDetailsOfpiPix {
    country: BelvoApi.EnumPaymentsCountry;
    /** The PIX key identifier of the bank account. */
    pixKey: string;
}
