/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Belvo from "..";

export interface BankAccountBusinessPse {
    /** Belvo's unique ID for the current bank account. */
    id: string;
    /** The ISO-8601 timestamp of when the data point was first created in Belvo's database. */
    createdAt: string;
    /** Belvo's unique ID for the user that created the bank account. */
    createdBy: string;
    /**
     * Belvo's unique ID for the customer associated with the bank account.
     * For `BUSINESS` bank accounts, this field is `null`.
     */
    customer?: string;
    /**
     * Belvo's unique ID for the institution that the bank account is created in.
     * For `BUSINESS` bank accounts that Belvo creates for organizations, this field is `null`.
     */
    institution?: string;
    /**
     * The bank account number of the payment beneficiary.
     *
     */
    number: string;
    holder: Belvo.HolderBusinessResponsePse;
    /** For PSE, this field will return an empty object. */
    details: Record<string, unknown>;
    /**
     * Optional and customizable object where you can provide any additional key-value pairs for your internal purposes. For example, an internal reference number for the payment intent.
     *
     * ⚠️ **Note**: You can only provide up to 50 keys (keys can have up to 50 characters each and each value can be up to 500 characters). We do not support nested objects, only ASCII values.
     */
    metadata?: Record<string, unknown>;
}
