/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BelvoApi from "..";

export interface BeneficiaryBankAccountPse {
    /** Belvo's unique ID for the beneficiary bank account. */
    id?: string;
    /** Belvo's unique ID for the institution that the bank account is created in. */
    institution?: string;
    /** The bank account number. */
    number?: string;
    holder?: BelvoApi.HolderBusinessResponsePse;
}
