/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Belvo from "..";

export interface BeneficiaryBankAccountOfpi {
    /** Belvo's unique ID for the beneficiary bank account. */
    id: string;
    /** The ISO-8601 timestamp of when the data point was last updated in Belvo's database. */
    createdAt: string;
    /** Belvo's unique ID for the user that created the bank account. */
    createdBy: string;
    institution: Belvo.PaymentInstitution;
    details?: Belvo.BeneficiaryBankAccountOfpiDetails;
    holder: Belvo.HolderResponseOfpi;
}
