/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Additional data regarding the merchant involved in the transaction.
 *
 */
export interface CategorizationMerchantData {
    /** The URL to the merchant's logo. */
    logo?: string;
    /** The URL to the merchant's website. */
    website?: string;
    /** The name of the merchant. */
    merchantName?: string;
}
