/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The current status of the charge.
 *
 */
export type ChargeStatus = "PENDING" | "SUCCEEDED" | "FAILED";

export const ChargeStatus = {
    Pending: "PENDING",
    Succeeded: "SUCCEEDED",
    Failed: "FAILED",
} as const;
