/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Belvo from "..";

/**
 * Details about the payment method.
 */
export interface ChargePaymentMethodDetailsOfpi {
    openFinance?: Belvo.ChargePaymentMethodDetailsOfpiContent;
}
