/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BelvoApi from "..";

export interface CreateBankAccountOfpi {
    /** Belvo's unique ID for the institution that the bank account is created in. */
    institution: string;
    /** Information regarding the individual bank account holder. */
    holder: BelvoApi.BankAccountHolderRequestOfpi;
    /** Information regarding the bank account. */
    details: BelvoApi.CreateBankAccountOfpiDetails;
}
