/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BelvoApi from "..";

export interface CreatePaymentLinkPse {
    /**
     * Amount to be paid by your customer. For PSE, you can only send whole numbers. For example: `350000`.
     *
     * **Note:** You can send this value either as a string or an integer. Regardless of the type you choose to send the `amount` as, Belvo returns a string with two decimal points, separated by a period ( `.`). For example, `350000.00`.
     *
     */
    amount: BelvoApi.CreatePaymentLinkPseAmount;
    /**
     * Belvo's unique ID to reference the customer.
     *
     */
    customer: string;
    /**
     * The description of the payment.
     *
     */
    description: string;
    /** A list of payment method types allowed in this payment intent. For PSE, this value must be set to `pse`. */
    allowedPaymentMethodTypes?: BelvoApi.EnumPaymentLinkAllowedPaymentMethod[];
    provider: BelvoApi.EnumPaymentLinkProvider;
    paymentMethodDetails: BelvoApi.PaymentMethodDetailsPse;
    callbackUrls?: BelvoApi.PaymentLinkCallbackUrls;
    /**
     * The payment link expiration time. It allows the following formats to be sent through:
     *
     *   - whole number + `m` for x amount of minutes. For example: `15m` for 15 minutes.
     *   - whole number + `h` for x amount of hours. For example: `12h` for 12 hours.
     *   - whole number + `d` for x amount of days. For example: `30d` for 30 days.
     *
     *   ℹ️ The minimum expiration time allowed for a payment link is `1m` (1 minute) and the maximum is `90d` (90 days).
     */
    expiresIn?: string;
}
