/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BelvoApi from "..";

export type DetailTaxReturnResponse =
    | BelvoApi.TaxReturnPersonal
    | BelvoApi.TaxReturnPersonalMonthly
    | BelvoApi.TaxReturnBusiness
    | BelvoApi.TaxReturnBusinessMonthly;
