/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BelvoApi from "..";

/**
 * Object containing form fields for the required credentials (for example, `username` or `password`) in this step.
 */
export interface DisplayCredentialsRequiredContentPse {
    payerInstitution?: BelvoApi.PaymentInstitution;
}
