/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BelvoApi from "..";

/**
 * Object detailing what payment method information you need to display.
 */
export interface DisplayCustomerBankAccountsContentPse {
    /** Array of customer bank account objects. */
    customerBankAccounts?: BelvoApi.PaymentMethodInfoCustomerBankAccountsPse[];
    beneficiaryBankAccount?: BelvoApi.BeneficiaryBankAccountPse;
}
