/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Belvo from "..";

/**
 * Object detailing the next steps you should follow for a specific `next_step` type.
 */
export interface DisplayConfirmationRequiredContentPse {
    payerInstitution?: Belvo.PaymentInstitution;
}
