/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BelvoApi from "..";

/**
 * Object detailing what payment method information you need to display.
 */
export interface DisplayPaymentMethodInformationContentOfpi {
    /** An array of institution objects. */
    institutions?: BelvoApi.PaymentInstitution[];
}
