/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Belvo from "..";

/**
 * Details regarding the payer institution.
 */
export interface DisplayPaymentFailed {
    payerInstitution?: Belvo.PaymentInstitution;
}
