/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BelvoApi from "..";

/**
 * Details regarding the personal information of the individual.
 */
export interface EmploymentRecordPersonalData {
    /**
     * The legal name of the individual
     *
     */
    officialName?: string;
    /**
     * The first name of the individual.
     *
     */
    firstName?: string;
    /**
     * The last name of the individual.
     *
     */
    lastName?: string;
    /**
     * The email address of the individual (as provided in the initial POST request).
     *
     */
    email?: string;
    /**
     * The date of the birth of the individual, in `YYYY-MM-DD` format.
     *
     */
    birthDate?: string;
    entitlements?: BelvoApi.EmploymentRecordEntitlement;
    /** Details regarding the individual's ID documents. */
    documentIds?: BelvoApi.EmploymentRecordDocumentId[];
}
