/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BelvoApi from "..";

/**
 * Details regarding the individual's ID documents.
 */
export interface EmploymentRecordDocumentId {
    documentType?: BelvoApi.EnumEmploymentRecordDocumentType;
    /**
     * The ID document's number (as a string).
     *
     */
    documentNumber?: string;
}
