/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type EnumTaxRetentionReceiverNationality = "NATIONAL" | "FOREIGN";

export const EnumTaxRetentionReceiverNationality = {
    National: "NATIONAL",
    Foreign: "FOREIGN",
} as const;
