/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of institution. We return one of the following values:
 *
 *   - `bank`
 *   - `fiscal`
 *   - `employment`
 *
 */
export type EnumInstitutionType = "bank" | "fiscal" | "employment";

export const EnumInstitutionType = {
    Bank: "bank",
    Fiscal: "fiscal",
    Employment: "employment",
} as const;
