/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Type of bank account holder. For PSE, this value must be `INDIVIDUAL`.
 */
export type EnumPaymentIntentHolderTypePse = "INDIVIDUAL" | "BUSINESS";

export const EnumPaymentIntentHolderTypePse = {
    Individual: "INDIVIDUAL",
    Business: "BUSINESS",
} as const;
