/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type EnumEmploymentRecordDocumentType = "NSS" | "CURP";

export const EnumEmploymentRecordDocumentType = {
    Nss: "NSS",
    Curp: "CURP",
} as const;
