/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type EnumIncomeVerificationType = "INFLOW";

export const EnumIncomeVerificationType = {
    Inflow: "INFLOW",
} as const;
