/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of bank account. Can be either `INDIVIDUAL` or `BUSINESS`.
 */
export type EnumBankAccountHolderTypeOfpi = "INDIVIDUAL" | "BUSINESS";

export const EnumBankAccountHolderTypeOfpi = {
    Individual: "INDIVIDUAL",
    Business: "BUSINESS",
} as const;
