/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The link type.
 * For more information, see our [Links](https://developers.belvo.com/docs/links-and-institutions#links) article.
 * We return one of the following enum values:
 *   - `single`
 *   - `recurrent`
 *   - `null`
 *
 */
export type EnumLinkAccessModeResponse = string | undefined;
