/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The portfolio type.
 *
 * We return one of the following values:
 *
 *   - `FIXED_INCOME`
 *   - `OTHER`
 *   - `PENSION`
 *   - `VARIABLE_INCOME`
 *
 */
export type EnumInvestmentPortfolioType = "FIXED_INCOME" | "OTHER" | "PENSION" | "VARIABLE_INCOME";

export const EnumInvestmentPortfolioType = {
    FixedIncome: "FIXED_INCOME",
    Other: "OTHER",
    Pension: "PENSION",
    VariableIncome: "VARIABLE_INCOME",
} as const;
