/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type EnumInvoiceSatInvoiceType = "Egreso" | "Ingreso" | "N\u00F3mina" | "Pago" | "Traslado";

export const EnumInvoiceSatInvoiceType = {
    Egreso: "Egreso",
    Ingreso: "Ingreso",
    Nomina: "N\u00F3mina",
    Pago: "Pago",
    Traslado: "Traslado",
} as const;
