/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The customer's country of residence.
 *
 *
 * -  BRA (🇧🇷 Brazil)
 * -  COL (🇨🇴 Colombia)
 *
 */
export type EnumPaymentsCountry = "BRA" | "COL";

export const EnumPaymentsCountry = {
    Bra: "BRA",
    Col: "COL",
} as const;
