/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type EnumRecurringExpensePaymentType = "SUBSCRIPTION" | "REGULAR";

export const EnumRecurringExpensePaymentType = {
    Subscription: "SUBSCRIPTION",
    Regular: "REGULAR",
} as const;
