/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of account holder.
 * Can be either:
 *
 *   - `INDIVIDUAL`
 *   - `BUSINESS`
 */
export type EnumCategorizationAccountHolderType = "INDIVIDUAL" | "BUSINESS";

export const EnumCategorizationAccountHolderType = {
    Individual: "INDIVIDUAL",
    Business: "BUSINESS",
} as const;
