/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of fee applied to the transaction. We return one of the following values:
 *
 *   - `TRANSACTION_FEE`
 */
export type EnumReceivableTransactionFeeType = "TRANSACTION_FEE";

export const EnumReceivableTransactionFeeType = {
    TransactionFee: "TRANSACTION_FEE",
} as const;
