/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Object containing the general fiscal situation of the taxpayer.
 */
export interface EquityStatementIndividual {
    /** The total gross equity of the tax payer. */
    totalGrossEquity: number;
    /** The total debts of the tax_payer */
    totalDebts: number;
    /** The total net equity value of the taxpayer. */
    totalNetEquity: number;
}
