/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Belvo from "..";

export interface EyodIncomeVerificationBodyRequest {
    /** Your unique ID for the income. */
    transactionId: string;
    accountHolderType: Belvo.EnumIncomeVerificationAccountHolderType;
    /** Your unique ID for the account holder, in UUID format. */
    accountHolderId: string;
    /** Your unique ID for the account where the transaction occurred. */
    accountId: string;
    accountCategory: Belvo.EnumIncomeVerificationAccountCategory;
    /** The date when the income transaction occurred, in `YYYY-MM-DD` format. */
    valueDate: string;
    /** The description of the income. */
    description: string;
    type?: Belvo.EnumIncomeVerificationType;
    /** The income amount. */
    amount: number;
    /**
     * The three-letter currency code of the income. For example:
     *
     *   • 🇧🇷 BRL (Brazilian Real)
     *   • 🇨🇴 COP (Colombian Peso)
     *   • 🇲🇽 MXN (Mexican Peso)
     */
    currency: string;
    /**
     * The institution where the account is registered.
     *
     * **Note:** This is the name that you use in your system to identify the institution. For example BBVA Retail.
     */
    institution: string;
}
