/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BelvoApi from "..";

/**
 * Additional information about the bank account holder required in order to create the account for OFPI.
 */
export interface HolderInformationBusinessOfpi {
    /** The bank account holder's first name. */
    name: string;
    identifierType: BelvoApi.EnumCustomerIdentifierTypeOfpi;
    /** The document number of the company's ID. */
    identifier: string;
}
