/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Belvo from "..";

export interface HolderInformationBusinessOfpiResponse {
    /** The bank account holder's first name. */
    name: string;
    identifierType: Belvo.EnumCustomerIdentifierTypeOfpi;
    /** The document number of the company's ID. */
    identifier: string;
}
