/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Object with additional information about the individual that holds the bank account.
 */
export interface HolderBankAccountInformationPse {
    /** The account holder's first name. */
    firstName?: string;
    /** The account holder's last name. */
    lastName?: string;
}
