/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BelvoApi from "..";

/**
 * Details regarding the bank account holder.
 */
export interface HolderResponseOfpi {
    type: BelvoApi.EnumBankAccountHolderTypeOfpi;
    information: BelvoApi.HolderResponseOfpiInformation;
}
