/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BelvoApi from "..";

/**
 * Additional information about the bank account holder required in order to create the account for OFPI.
 */
export interface HolderInformationIndividualOfpi {
    /** The bank account holder's first name. */
    firstName: string;
    /** The bank account holder's last name. */
    lastName: string;
    identifierType: BelvoApi.EnumCustomerIdentifierTypeOfpi;
    /** The document number of the customer's ID. */
    identifier: string;
}
