/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Belvo from "..";

/**
 * Details regarding the bank account holder.
 */
export interface HolderResponseOfpi {
    type: Belvo.EnumBankAccountHolderTypeOfpi;
    information: Belvo.HolderResponseOfpiInformation;
}
