/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface HolderInformationBusinessPse {
    /**
     * The business name.
     *
     * Note, this is only applicable if the `holder.type` is set to `BUSINESS`.
     */
    name: string;
}
