/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Belvo from "..";

/**
 * Income insights
 */
export interface Income {
    /** Belvo's unique identifier for the current income. */
    id: string;
    /** The `link.id` the account belongs to. */
    link: string;
    /** The ISO-8601 timestamp of when the data point was created in Belvo's database. */
    createdAt: string;
    /** An array of enriched income stream objects. */
    incomeStreams: Belvo.IncomeStreamsBody[];
    incomeSourceType: Belvo.EnumIncomeSourceType;
    /**
     * The date when the first transaction occurred, in `YYYY-MM-DD` format.
     *
     */
    firstTransactionDate?: string;
    /**
     * The date when when the last transaction occurred, in `YYYY-MM-DD` format.
     *
     */
    lastTransactionDate: string;
    /**
     * Number of total income streams analized.
     *
     */
    numberOfIncomeStreams: number;
    /**
     * Average amount of income received per month across all the accounts for the specific user.
     *
     */
    monthlyAverage: number;
    /**
     * Average amount of regular income (with a frequency of `MONTHLY`, `FORTNIGHTLY`, or `WEEKLY`) received per month for the specific user.
     *
     */
    monthlyAverageRegular: number;
    /**
     * Average amount of irregular income (with a frequency of `SINGLE` or `IRREGULAR`) received per month for the specific user.
     *
     */
    monthlyAverageIrregular: number;
    /**
     * Average amount of income received per month for the specific user with `LOW` confidence.
     *
     */
    monthlyAverageLowConfidence: number;
    /**
     * Average amount of income received per month for the specific user with `MEDIUM` confidence.
     *
     */
    monthlyAverageMediumConfidence: number;
    /**
     * Average amount of income received per month for the specific user with `HIGH` confidence.
     *
     */
    monthlyAverageHighConfidence: number;
    /**
     * Total amount of all income received for the specific user.
     *
     */
    totalIncomeAmount: number;
    /**
     * Total amount of regular income (with a frequency of `MONTHLY`, `FORTNIGHTLY`, `WEEKLY`) for the specific user.
     *
     */
    totalRegularIncomeAmount: number;
    /**
     * Total amount of irregular income (with a frequency of `SINGLE` or `IRREGULAR`) for the specific user.
     *
     */
    totalIrregularIncomeAmount?: number;
    /**
     * Total amount of income for the specific user with `LOW` confidence.
     *
     */
    totalLowConfidence: number;
    /**
     * Total amount of income for the specific user with `MEDIUM` confidence.
     *
     */
    totalMediumConfidence: number;
    /**
     * Total amount of income for the specific user with `HIGH` confidence.
     *
     */
    totalHighConfidence: number;
}
