/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface InstitutionsFeature {
    /** The name of the feature. */
    name?: string;
    /** The description of the feature. */
    description?: string;
}
