/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BelvoApi from "..";

export interface InstitutionFormField {
    /** The username, password, or username type field. */
    name?: string;
    /** The input type for the form field. For example, string. */
    type?: string;
    /**
     * The label of the form field. For example:
     * - Document
     * - Clave
     * - Token
     *
     */
    label?: string;
    /** The type of input validation used for the field. */
    validation?: string;
    /** The placeholder text in the form field. */
    placeholder?: string;
    /** The message displayed when an invalid input is provided in the form field. */
    validationMessage?: string;
    /** Array of additional form field values. */
    values?: BelvoApi.InstitutionsFormFieldValues[];
    /** Number of digits allowed when the type is `token`. */
    length?: number;
    /** It indicates whether this form field is optional. */
    optional?: boolean;
}
