/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BelvoApi from "..";

/**
 * Details regarding the institution.
 */
export interface InstitutionAccount {
    /**
     * The name of the institution, as designated by Belvo.
     * Please see our [Institutions](https://developers.belvo.com/docs/institution) DevPortal article for a detailed list of institution names.
     */
    name?: string;
    type?: BelvoApi.EnumInstitutionType;
}
