/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This error occurs when you try to update a link from single to recurrent, but there are no login credentials stored for the user.
 */
export interface InvalidAccessMode {
    /**
     * A unique error code (`invalid_access_mode_switch`) that allows you to classify and handle the error programmatically.
     *
     * ℹ️ Check our DevPortal for more information on how to handle <a href="https://developers.belvo.com/docs/belvo-api-errors#400-invalid_access_mode_switch" target="_blank">400 invalid_access_mode_switch errors</a>.
     */
    code?: string;
    /**
     * A short description of the error.
     *
     * For `invalid_access_mode_switch` errors, the description is:
     *
     *   - `This link doesn't have stored credentials hence it can't be switched to recurrent mode"`.
     */
    message?: string;
    /** A 32-character unique ID of the request (matching a regex pattern of: `[a-f0-9]{32}`). Provide this ID when contacting the Belvo support team to accelerate investigations. */
    requestId?: string;
}
