/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The public identifiers for the instrument.
 */
export interface InvestmentsPortfolioInstrumentPublicId {
    /** The type of public identifier for the instrument. */
    type: string;
    /** The value of the `public_id.type`. */
    value: string;
}
