/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface InvestmentsPortfolioInstrumentInterestRate {
    /** How often the interest rate is calculated on the instrument. */
    type: string;
    /**
     * The interest rate for the instrument, in percent.
     *
     *
     * ℹ️  **Note:** If the `interest_rate.index` is present, this value is a percentage of the index. For example, if `interest_rate.index` = `CDI` and `interest_rate.value` = `90`, then the total interest rate applied is 90% of the CDI.
     *
     */
    value: number;
    /** If applicable, the index type that the `interest_rates.value` is calculated against. */
    index?: string;
}
