/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface InvestmentsPortfolioInstrumentRedemptionConditions {
    /** The name of the redemption condition. */
    type: string;
    /** The value of `redemption_conditions.type`. */
    value: string;
}
