/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Information about the error you ran into in the previous step of the payment intent, if applicable. This error can occur when the MFA token your customer provides is invalid.
 */
export interface LastErrorInvalidToken {
    /** A unique error code (`invalid_token`) that allows you to classify and handle the error programmatically. */
    errorCode: string;
    /** A short description of the error. */
    errorMessage: string;
}
