/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ListPaymentLinksRequestStatus = "ACTIVE" | "INACTIVE";

export const ListPaymentLinksRequestStatus = {
    Active: "ACTIVE",
    Inactive: "INACTIVE",
} as const;
