/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface OwnerDocumentId {
    /**
     * The type of document the owner provided to the institution to open the account. Common document types are:
     *
     * 🇧🇷 Brazil
     * - `CPF` (*Cadastro de Pessoas Físicas*)
     * - `CNPJ`(*Cadastro Nacional de Pessoas Jurídicas*)
     *
     * 🇨🇴 Colombia
     * - `CC`(*Cédula de Ciudadanía*)
     * - `NIT` (*Número de Identificación Tributaria*)
     *
     * 🇲🇽 Mexico
     * - `CURP` (*Clave Única de Registro de Población*)
     * - `NISS` (*Número de Seguridad Social*)
     *
     */
    documentType?: string;
    /** The document's identification number. */
    documentNumber?: string;
}
