/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A JSON object containing a session UUID and a MFA token
 */
export interface PatchBody {
    /** The session you want to resume. You need to use the `session` value that is provided in the 428 Token Required response that you receive after you make your POST request. */
    session: string;
    /** The MFA token generated by the institution and required to continue a session. */
    token?: string;
    /** The `link.id` you want to resume. Must be the same `link.id` as the one you receive in the 428 Token Required response that contains the `session` ID. */
    link: string;
    /**
     * Indicates whether or not to persist the data in Belvo. By default, this is set to `true` and we return a 201 Created response.
     * When set to `false`, the data won't be persisted and we return a 200 OK response.
     */
    saveData?: boolean;
}
