/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PaymentLinkCallbackUrls {
    /**
     * The URL that the user should be redirected to if they decide to cancel the payment process or if an error occurs.
     *
     * **Note:** Not required if your integration only generates payment links through the [Belvo Dashboard](https://dashboard.belvo.com/).
     */
    cancel?: string;
    /**
     * The URL that the user should be redirected to when they complete the payment process successfully.
     *
     * **Note:** Not required if your integration only generates payment links through the [Belvo Dashboard](https://dashboard.belvo.com/).
     */
    success?: string;
}
