/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BelvoApi from "..";

/**
 * Object with information required by Open Finance Payments in Brazil to create a payment intent.
 */
export interface PaymentMethodDetailsOfpi {
    openFinance: BelvoApi.PaymentLinksPaymentMethodDetailsBodyOfpi;
}
