/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Belvo from "..";

/**
 * Object with information required by PSE to create a payment intent.
 */
export interface PaymentMethodDetailsPse {
    pse: Belvo.PaymentLinksPaymentMethodDetailsBodyPse;
}
