/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Details about the organization's bank account that will receive the payment.
 */
export interface PaymentLinksPaymentMethodDetailsBodyOfpi {
    /** Belvo's unique ID used to identify the beneficiary's bank account. */
    beneficiaryBankAccount: string;
    /** The URL to your application that your customer will be directed to once they confirm the payment in their bank application. */
    callbackUrl?: string;
}
