/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Belvo from "..";

export interface PaymentLinkPse {
    /** Belvo's unique ID for the current payment link. */
    id: string;
    /** The ISO-8601 timestamp of when the data point was last updated in Belvo's database. */
    createdAt: string;
    /** Belvo's unique ID for the user that created the payment link. */
    createdBy: string;
    /** The URL for the hosted-widget that will guide your user through the payments process. */
    paymentUrl: string;
    /**
     * The Belvo-generated access token for the payment link.
     *
     * **Note:** You'll need the `access_token` to make [Get details for a payment link](https://developers.belvo.com/reference/detailcreatepaymentlink) requests.
     */
    accessToken?: string;
    callbackUrls: Belvo.PaymentLinkCallbackUrlsResponse;
    paymentIntent?: Belvo.PaymentIntentPse;
    /**
     * The ISO-8601 timestamp of when the payment link was last updated.
     *
     */
    updatedAt?: string;
    status: Belvo.EnumPaymentLinksStatus;
    /** The payment link expiration time. */
    expiresIn: string;
    /**
     * The ISO-8601 timestamp of when the payment link is set to expire.
     *
     */
    expiresAt: string;
}
