/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BelvoApi from "..";

export interface PaymentTransaction {
    /** Belvo’s unique ID to reference the transaction. */
    id: string;
    /** The ISO-8601 timestamp of when the data point was last updated in Belvo's database. */
    createdAt: string;
    /** Belvo's unique ID for the user that created the payment. */
    createdBy: string;
    /**
     * The transaction amount.
     *
     *
     * **Note**: The amount displayed is always positive as we indicate the direction of the transaction in `transaction_type` parameter.
     *
     */
    amount: string;
    currency: BelvoApi.EnumPaymentsCurrency;
    /**
     * The description of the payment.
     *
     */
    description: string;
    transactionType: BelvoApi.EnumPaymentTransactionType;
    /** Belvo's unique ID used to identify the beneficiary's bank account. */
    beneficiary: string;
    payer: BelvoApi.PaymentTransactionPayer;
    /** The unique ID of the payment intent associated with the transaction. */
    paymentIntent?: string;
    /** Belvo's unique ID for the customer asscociated with this transaction. */
    customer?: string;
}
