/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Details about the payment method type selected.
 */
export interface PaymentIntentPaymentMethodDetailsBodyPse {
    /** Belvo's unique identifier for the payer’s institution. */
    payerInstitution?: string;
    /** Belvo's unique ID used to identify the customer’s bank account. */
    payerBankAccount?: string;
    /** Belvo's unique ID used to identify the beneficiary’s bank account. */
    beneficiaryBankAccount: string;
    /** The username used to log in to the institution. This value is obfuscated. */
    username?: string;
    /** The password used to log in to the institution. This value is obfuscated. */
    password?: string;
    /** The callback URL that your user will be redirected to after confirming the payment in their banking application. */
    callbackUrl: string;
    /** This parameter determines the payment flow of the payment intent. By default, this is set to `true` and the payment intent created is processed using the Belvo's payment flow and Belvo-integrated institutions. When set to `false`, the payment intent process uses institutions not integrated into Belvo's flow. */
    belvoFlow: boolean;
}
