/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Payment method type selected.
 */
export interface PaymentIntentPaymentMethodDetailsBodyIndividualOfpi {
    /** Belvo's unique ID used to identify the beneficiary's bank account. */
    beneficiaryBankAccount: string;
    /** Belvo's unique ID to reference the payer's institution. */
    payerInstitution: string;
    /** The callback URL that your user will be redirected to after confirming the payment in their banking application. */
    callbackUrl: string;
    /**
     * The customer's CPF number. Only required when the `customer_type` is `BUSINESS`.
     *
     * **Note:** This value is obfuscated.
     */
    cpf?: string;
}
