/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Belvo from "..";

export type PaymentIntentOfpiPaymentMethodDetails =
    | Belvo.PaymentIntentPaymentMethodDetailsIndividualOfpi
    | Belvo.PaymentIntentPaymentMethodDetailsBusinessOfpi;
