/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BelvoApi from "..";

export type PaymentIntentPseLastError =
    | BelvoApi.LastErrorInvalidCredentials
    | BelvoApi.LastErrorInvalidToken
    | BelvoApi.LastErrorLoginError
    | BelvoApi.LastErrorTwoFactor
    | BelvoApi.LastErrorPaymentError
    | BelvoApi.LastErrorSessionExpired;
