/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BelvoApi from "..";

/**
 * Object with payment method details to create a payment intent.
 */
export interface PaymentIntentsPaymentMethodDetailsPse {
    pse: BelvoApi.PaymentIntentsPaymentMethodDetailsBodyPse;
}
