/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Object containing the tax payer's total pension income.
 */
export interface PensionIncomeStatementIndividual {
    /** The total net pension of the taxpayer. */
    netPensionIncome: number;
    /** The total taxable pension income of the taxpayer. */
    netTaxablePensionIncome: number;
}
