/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface RecurringExpenseSourceTransaction {
    /** The transaction amount. */
    amount: number;
    /** The description of the transaction provided by the institution. Usually, this is the text that the end user would see in the bank statement. The description can be an empty string. */
    description?: string;
    /** The date when the transaction occurred, in `YYYY-MM-DD` format. */
    valueDate: string;
}
