/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Object containing information about where the tax payer reports their income.
 */
export interface ReportingId {
    /** The type of reporting ID. For DIAN, this is the sectional address code (*Codigo Dirrecion Seccional*) */
    reportingType: string;
    /** The value of the reporting ID. */
    reportingValue: string;
}
