/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Belvo has a limit regarding the time it takes to log in, retrieve account data, and log out. A timeout occurs when there is a very high amount of data and everything could not be obtained within the allotted time.
 */
export interface RequestTimeoutError {
    /**
     * A unique error code (`request_timeout`) that allows you to classify and handle the error programmatically.
     *
     * ℹ️ Check our DevPortal for more information on how to handle <a href="https://developers.belvo.com/docs/belvo-api-errors#408-request_timeout" target="_blank">408 request_timeout errors</a>.
     */
    code?: string;
    /**
     * A short description of the error.
     *
     * For `request_timeout` errors, the description is:
     *
     *   - `The request timed out, you can retry asking for less data by changing your query parameters`.
     */
    message?: string;
    /** A 32-character unique ID of the request (matching a regex pattern of: `[a-f0-9]{32}`). Provide this ID when contacting the Belvo support team to accelerate investigations. */
    requestId?: string;
}
