/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BelvoApi from "..";

export interface RiskInsights {
    /** Belvo's unique ID for the risk insights request. */
    id: string;
    /** The `link.id` the risk insights analysis belongs to. */
    link: string;
    /** An array of Belvo-generated account numbers (UUIDs) that were used during the risk insights analysis. If no accounts were found, we return an empty array. */
    accounts?: string[];
    /** The ISO-8601 timestamp of when the data point was last updated in Belvo's database. */
    createdAt: string;
    transactionsMetrics: BelvoApi.RiskInsightsTransactionMetrics;
    balancesMetrics: BelvoApi.RiskInsightsBalanceMetrics;
    cashflowMetrics: BelvoApi.RiskInsightsCashflowMetrics;
    creditCardsMetrics: BelvoApi.RiskInsightsCreditCardMetrics;
    loansMetrics: BelvoApi.RiskInsightsLoansMetrics;
}
