/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Aggregated metrics calculated based on the user's transactions from checking, savings, credit, and loan accounts.
 *
 * However, internal transfers (transfers between accounts belonging to the same link) are not used in the calculation.
 *
 */
export interface RiskInsightsCashflowMetrics {
    /**
     * Sum total of all transactions leading to a positive cashflow in the last week (counted from the time of the request).
     *
     */
    sumPositive1W?: number;
    /**
     * Sum total of all transactions leading to a positive cashflow in the last month (counted from the time of the request).
     *
     */
    sumPositive1M?: number;
    /**
     * Sum total of all transactions leading to a positive cashflow in the last three months (counted from the time of the request).
     *
     */
    sumPositive3M?: number;
    /**
     * Sum total of all transactions leading to a negative cashflow in the last week (counted from the time of the request).
     *
     */
    sumNegative1W?: number;
    /**
     * Sum total of all transactions leading to a negative cashflow in the last month (counted from the time of the request).
     *
     */
    sumNegative1M?: number;
    /**
     * Sum total of all transactions leading to a negative cashflow in the last three months (counted from the time of the request).
     *
     */
    sumNegative3M?: number;
    /**
     * The ratio between sum_positive / sum_negative  in the last week (counted from the time of the request).
     *
     * ℹ️ If the ratio is greater than `1`, it means that the user has more income than outgoing, indicating that they spend less than they earn.
     *
     * **Note**: In the case that there have been no outgoing transactions, the value will be `null`.
     *
     */
    positiveToNegativeRatio1W?: number;
    /**
     * The ratio between sum_positive / sum_negative  in the last month (counted from the time of the request).
     *
     * ℹ️ If the ratio is greater than `1`, it means that the user has more income than outgoing, indicating that they spend less than they earn.
     *
     */
    positiveToNegativeRatio1M?: number;
    /**
     * The ratio between sum_positive / sum_negative  in the last three months (counted from the time of the request).
     *
     * ℹ️ If the ratio is greater than `1`, it means that the user has more income than outgoing, indicating that they spend less than they earn.
     *
     */
    positiveToNegativeRatio3M?: number;
}
