/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface RiskInsightsCreditCardMetrics {
    /**
     * Number of credit cards accounts associated to the link.
     *
     */
    numAccounts: number;
    /**
     * Sum total of all credit cards' limits.
     *
     */
    sumCreditLimit?: number;
    /**
     * Sum total of all credit used.
     *
     */
    sumCreditUsed?: number;
}
