/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SecretKeys {
    /** Belvo's unique ID for the Payments API `secretId`. */
    id: string;
    /** Your Payments API `secretPassword`. This value is obfuscated. */
    password: string;
    /**
     * The ISO-8601 timestamp of when the secret key was created.
     *
     */
    createdAt: string;
    /**
     * The ISO-8601 timestamp of when the secret key was last used.
     *
     */
    lastUsed: string;
}
