/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface StandardRequest {
    /** The `link.id` that you want to get information for. */
    link: string;
    /** The OTP token generated by the bank. */
    token?: string;
    /**
     * Indicates whether or not to persist the data in Belvo. By default, this is set to `true` and we return a 201 Created response.
     * When set to `false`, the data won't be persisted and we return a 200 OK response.
     */
    saveData?: boolean;
}
