/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Object containing the calculated tax assessment of the tax payer. This includes the total taxable income, the income tax applied, and taxes already withheld.
 */
export interface TaxAssessmentBusiness {
    /** The net income on which tax can be applied. */
    netIncomeTaxable: number;
    /** The tax applied on your unexpected income (such as lottery wins or house sales). */
    fortuitousProfitTax: number;
    /** The calculated total tax that can be applied on the tax payer's taxable income (total income - exemptions - deductions). */
    totalTaxOnTaxableNetIncome: number;
    /** After additional deductions that you can apply, this will be the net income tax. If no further deduction are identified, this value will be the same as `total_tax_on_taxable_net_income`. */
    netIncomeTax: number;
    /** After further deductions, this is the final calculated tax that the taxpayer is required to pay. */
    totalTaxDue: number;
    /** How much the tax payer has already paid througout the fiscal year. */
    totalWithholdingsForTheTaxableYearToBeDeclared: number;
    /** How much the tax payer is required to pay. */
    totalBalancePayable: number;
    /** How much the tax payer is expected to receive. */
    totalBalanceInFavor: number;
    /** The total the tax payer is required to pay, taking into account deductions and fiscal credits. */
    totalPayment: number;
}
