/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BelvoApi from "..";

export interface TaxDeclarationIndividual {
    /** Belvo's unique ID for the current tax declaration. */
    id: string;
    /** Belvo's unique ID of the user that this tax declaration is associated with. */
    link: string;
    /** The ISO-8601 timestamp when the data point was collected. */
    collectedAt: string;
    /** The ISO-8601 timestamp of when the data point was last updated in Belvo's database. */
    createdAt: string;
    documentInformation: BelvoApi.DocumentInformationIndividual;
    taxPayerInformation: BelvoApi.TaxPayerInformationIndividual;
    equityStatement: BelvoApi.EquityStatementIndividual;
    annualIncomeStatement: BelvoApi.AnnualIncomeStatementIndividual;
    pensionIncomeStatement: BelvoApi.PensionIncomeStatementIndividual;
    taxAssessment: BelvoApi.TaxAssessmentIndividual;
    /** The date the tax declaration was issued by the fiscal institution. */
    dateIssued: string;
    /** The PDF of the tax declaration, as a binary string. */
    pdf?: string;
}
