/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Belvo from "..";

/**
 * Object containing information about the tax payer.
 */
export interface TaxPayerInformationBusiness {
    /** The tax payer's first last name. */
    firstLastName?: string;
    /** The tax payer's second last name. */
    secondLastName?: string;
    /** The tax payer's first name. */
    firstName?: string;
    /** Additional names of the tax payer. */
    otherNames?: string;
    /** The name of the company, as registered at the institution. */
    companyName: string;
    /** The main economic activity the tax payer is involved in. */
    mainEconomicActivity: string;
    documentId: Belvo.DocumentIdBusiness;
    reportingId: Belvo.ReportingId;
}
