/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface TaxReturnBusinessMonthly {
    /** Unique identifier created by Belvo used to reference the current Tax Return. */
    id?: string;
    /** The ISO-8601 timestamp when the data point was collected. */
    collectedAt?: string;
    /** The ISO-8601 timestamp of when the data point was last updated in Belvo's database. */
    createdAt?: string;
    /** General information regarding the tax return (year, RFC, return type, person/company name, and so on). */
    informacionGeneral?: Record<string, unknown>;
    /** Information used to calculate the provisional income tax for the period. */
    determinacionIsr?: Record<string, unknown>;
    /** Information on the monthly provisional payments for the income tax. */
    detallePagoIsr?: Record<string, unknown>;
    /** Information used to calculate the provisional VAT tax for the period. */
    determinacionIva?: Record<string, unknown>;
    /** Information on the monthly provisional payments for the VAT tax. */
    detallePagoIva?: Record<string, unknown>;
    /** Tax return PDF as a binary. */
    pdf?: string;
    /** The acknowledgement receipt from the fiscal institution confirming that they received the tax return. */
    receiptPdf?: string;
    /** The type of tax return. Can be either monthly or annual. */
    type?: string;
}
