/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BelvoApi from "..";

export interface TaxRetentions {
    /** Belvo's unique identifier used to reference the current tax retention statement. */
    id?: string;
    /** The `link.id` the tax retention belongs to. */
    link?: string;
    /**
     * The ISO-8601 timestamp of when the data point was collected.
     *
     */
    collectedAt?: string;
    /**
     * The ISO-8601 timestamp of when the data point was last updated in Belvo's database.
     *
     */
    createdAt?: string;
    /**
     * The fiscal institution's unique ID for the invoice that the tax retention relates to.
     *
     */
    invoiceIdentification?: string;
    /**
     * The CFDI version of the tax retentions.
     *
     */
    version?: string;
    /**
     * The tax retention code. For more information, see our [SAT Catalogs DevPortal article](https://developers.belvo.com/docs/sat-catalogs#retention-code).
     *
     */
    code?: number;
    /**
     * The ISO-8601 timestamp of when the tax retention was issued.
     *
     */
    issuedAt?: string;
    /**
     * The ISO-8601 timestamp of when the tax retention was certified.
     *
     */
    certifiedAt?: string;
    /**
     * The ISO-8601 timestamp of when the tax retention was canceled (if applicable).
     *
     */
    cancelledAt?: string;
    /**
     * The fiscal ID of the invoice sender.
     *
     */
    senderId?: string;
    /**
     * The name of the invoice sender.
     *
     */
    senderName?: string;
    receiverNationality: BelvoApi.EnumTaxRetentionReceiverNationality;
    /**
     * The fiscal ID of the invoice receiver.
     *
     */
    receiverId?: string;
    /**
     * The name of the invoice receiver.
     *
     */
    receiverName?: string;
    /**
     * The total amount of the invoice that the tax retention relates to.
     *
     */
    totalInvoiceAmount?: number;
    /**
     * Total amount that is exempt from taxation.
     *
     */
    totalExemptAmount?: number;
    /**
     * Total tax retained.
     *
     */
    totalRetainedAmount?: number;
    /**
     * The total amount that can be taxed. Calculated as `total_invoice_amount` - `total_exempt_amount`.
     *
     */
    totalTaxableAmount?: number;
    /** A breakdown of the retained taxes. */
    retentionBreakdown?: BelvoApi.RetentionBreakdown[];
    /**
     * The tax retention document in XML form.
     *
     */
    xml?: string;
}
