/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Belvo from "..";

export interface TaxStatusSat {
    /** Unique identifier created by Belvo used to reference the current Tax Status. */
    id: string;
    /** The `link.id` that the tax status is associated with. */
    link: string;
    /** The ISO-8601 timestamp when the data point was collected. */
    collectedAt?: string;
    /** The ISO-8601 timestamp of when the data point was last updated in Belvo's database. */
    createdAt: string;
    /** The place and date of that the tax status was issued. */
    placeAndDateOfIssuance?: string;
    /** The name of the person or business. */
    officialName?: string;
    /**
     * The taxpayer's *Cédula de Identificación Fiscal* (CIF) ID.
     *
     */
    idCif?: string;
    taxPayerInformation: Belvo.TaxStatusTaxPayerInformationSat;
    address: Belvo.TaxStatusAddressSat;
    /**
     * A list of economic activity objects.
     *
     */
    economicActivity?: Belvo.TaxStatusEconomicActivitySat[];
    /**
     * A list of regimen objects.
     *
     */
    regimes?: Belvo.TaxStatusRegimensSat[];
    /**
     * Details regarding a business's obligations.
     *
     * ℹ️ For non-business accounts, this field will return empty.
     *
     */
    obligations?: Belvo.TaxStatusObligationsSat[];
    /** The validation certificate of the document. */
    digitalStamp?: string;
    /**
     * A data chain containing the basic structure of a fiscal digital check. For Mexico, this is the *Comprobante Fiscal Digital por Internet* (CFDI).
     *
     */
    digitalStampChain?: string;
    /** Tax status PDF as a binary string. */
    pdf?: string;
}
