/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BelvoApi from "..";

export type TaxStatusPaginatedResponseResultsItem = BelvoApi.TaxStatusSat | BelvoApi.TaxStatusDian;
