/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface TaxStatusAddressBetweenStreetDian {
    /**
     * **Note**: This field is not applicable for DIAN Colombia and will return `null`.
     *
     */
    streetOne?: string;
    /**
     * **Note**: This field is not applicable for DIAN Colombia and will return `null`.
     *
     */
    streetTwo?: string;
}
