/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Details regarding a business's obligations.
 *
 * ℹ️ For non-business accounts, this field will return empty.
 *
 */
export interface TaxStatusObligationsSat {
    /**
     * The description of the obligation.
     *
     */
    obligation?: string;
    /**
     * The deadline to fulfill the obligation, as imposed by the tax authority.
     *
     */
    expiration?: string;
    /**
     * The date when obligation started.
     *
     */
    initialDate?: string;
    /**
     * The date when obligation ended.
     *
     */
    endDate?: string;
}
