/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface TaxStatusRegimensDian {
    /**
     * **Note**: This field is not applicable for DIAN Colombia and will return `null`.
     *
     */
    endDate?: string;
    /**
     * **Note**: This field is not applicable for DIAN Colombia and will return `null`.
     *
     */
    initialDate?: string;
    /** The description of the regimen. */
    regimen?: string;
}
