/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This error occurs when you try to access some data operation that Belvo does not support for an institution. For example, trying to access the Balances resource for fiscal institutions.
 */
export interface UnsupportedOperationError {
    /**
     * A unique error code (`unsupported_operation`) that allows you to classify and handle the error programmatically.
     *
     * ℹ️ Check our DevPortal for more information on how to handle <a href="https://developers.belvo.com/docs/belvo-api-errors#400-unsupported_operation" target="_blank">400 unsupported_operation errors</a>.
     */
    code?: string;
    /**
     * A short description of the error.
     *
     * For `unsupported_operation` errors, the description is:
     *
     *   - `The resource you are trying to access is not supported by this institution`.
     */
    message?: string;
    /** A 32-character unique ID of the request (matching a regex pattern of: `[a-f0-9]{32}`). Provide this ID when contacting the Belvo support team to accelerate investigations. */
    requestId?: string;
}
