/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as BelvoApi from "../../api";
import * as core from "../../core";

export const AccountsLoanDataFees: core.serialization.ObjectSchema<
    serializers.AccountsLoanDataFees.Raw,
    BelvoApi.AccountsLoanDataFees
> = core.serialization.object({
    type: core.serialization.lazy(async () => (await import("..")).EnumLoanDataFeeType),
    value: core.serialization.number(),
});

export declare namespace AccountsLoanDataFees {
    interface Raw {
        type: serializers.EnumLoanDataFeeType.Raw;
        value: number;
    }
}
