/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as BelvoApi from "../../api";
import * as core from "../../core";

export const BankAccountDetailsOpenFinance: core.serialization.ObjectSchema<
    serializers.BankAccountDetailsOpenFinance.Raw,
    BelvoApi.BankAccountDetailsOpenFinance
> = core.serialization.object({
    country: core.serialization.lazy(async () => (await import("..")).EnumPaymentsCountry),
    accountType: core.serialization.property(
        "account_type",
        core.serialization.lazy(async () => (await import("..")).EnumBankAccountPixAccountTypeOfpi)
    ),
    agency: core.serialization.string(),
    number: core.serialization.string(),
});

export declare namespace BankAccountDetailsOpenFinance {
    interface Raw {
        country: serializers.EnumPaymentsCountry.Raw;
        account_type: serializers.EnumBankAccountPixAccountTypeOfpi.Raw;
        agency: string;
        number: string;
    }
}
