/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Belvo from "../../api";
import * as core from "../../core";

export const BankAccountDetailsOfpiPix: core.serialization.ObjectSchema<
    serializers.BankAccountDetailsOfpiPix.Raw,
    Belvo.BankAccountDetailsOfpiPix
> = core.serialization.object({
    country: core.serialization.lazy(async () => (await import("..")).EnumPaymentsCountry),
    pixKey: core.serialization.property("pix_key", core.serialization.string()),
});

export declare namespace BankAccountDetailsOfpiPix {
    interface Raw {
        country: serializers.EnumPaymentsCountry.Raw;
        pix_key: string;
    }
}
