/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as BelvoApi from "../../api";
import * as core from "../../core";

export const ChargePaymentMethodDetailsOfpiContent: core.serialization.ObjectSchema<
    serializers.ChargePaymentMethodDetailsOfpiContent.Raw,
    BelvoApi.ChargePaymentMethodDetailsOfpiContent
> = core.serialization.object({
    payerInstitution: core.serialization.property("payer_institution", core.serialization.string().optional()),
    beneficiaryBankAccount: core.serialization.property(
        "beneficiary_bank_account",
        core.serialization.string().optional()
    ),
});

export declare namespace ChargePaymentMethodDetailsOfpiContent {
    interface Raw {
        payer_institution?: string | null;
        beneficiary_bank_account?: string | null;
    }
}
