/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Belvo from "../../api";
import * as core from "../../core";

export const ChargePaymentMethodDetailsPseContent: core.serialization.ObjectSchema<
    serializers.ChargePaymentMethodDetailsPseContent.Raw,
    Belvo.ChargePaymentMethodDetailsPseContent
> = core.serialization.object({
    payerInstitution: core.serialization.property("payer_institution", core.serialization.string().optional()),
    payerBankAccount: core.serialization.property("payer_bank_account", core.serialization.string().optional()),
});

export declare namespace ChargePaymentMethodDetailsPseContent {
    interface Raw {
        payer_institution?: string | null;
        payer_bank_account?: string | null;
    }
}
