/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as BelvoApi from "../../api";
import * as core from "../../core";

export const CreateCustomerResponse: core.serialization.Schema<
    serializers.CreateCustomerResponse.Raw,
    BelvoApi.CreateCustomerResponse
> = core.serialization.undiscriminatedUnion([
    core.serialization.lazyObject(async () => (await import("..")).CustomerOfpi),
    core.serialization.lazyObject(async () => (await import("..")).CustomerPse),
]);

export declare namespace CreateCustomerResponse {
    type Raw = serializers.CustomerOfpi.Raw | serializers.CustomerPse.Raw;
}
