/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as BelvoApi from "../../api";
import * as core from "../../core";

export const CreatePaymentlinkRequest: core.serialization.Schema<
    serializers.CreatePaymentlinkRequest.Raw,
    BelvoApi.CreatePaymentlinkRequest
> = core.serialization.undiscriminatedUnion([
    core.serialization.lazyObject(async () => (await import("..")).CreatePaymentLinkOfpi),
    core.serialization.lazyObject(async () => (await import("..")).CreatePaymentLinkPse),
]);

export declare namespace CreatePaymentlinkRequest {
    type Raw = serializers.CreatePaymentLinkOfpi.Raw | serializers.CreatePaymentLinkPse.Raw;
}
