/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as BelvoApi from "../../api";
import * as core from "../../core";

export const CreatePaymentLinkOfpiAmount: core.serialization.Schema<
    serializers.CreatePaymentLinkOfpiAmount.Raw,
    BelvoApi.CreatePaymentLinkOfpiAmount
> = core.serialization.undiscriminatedUnion([core.serialization.string(), core.serialization.number()]);

export declare namespace CreatePaymentLinkOfpiAmount {
    type Raw = string | number;
}
