/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as BelvoApi from "../../api";
import * as core from "../../core";

export const CreatePaymentlinkResponse: core.serialization.Schema<
    serializers.CreatePaymentlinkResponse.Raw,
    BelvoApi.CreatePaymentlinkResponse
> = core.serialization.undiscriminatedUnion([
    core.serialization.lazyObject(async () => (await import("..")).PaymentLinkOfpi),
    core.serialization.lazyObject(async () => (await import("..")).PaymentLinkPse),
]);

export declare namespace CreatePaymentlinkResponse {
    type Raw = serializers.PaymentLinkOfpi.Raw | serializers.PaymentLinkPse.Raw;
}
