/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Belvo from "../../api";
import * as core from "../../core";

export const CreatePaymentLinkOfpi: core.serialization.ObjectSchema<
    serializers.CreatePaymentLinkOfpi.Raw,
    Belvo.CreatePaymentLinkOfpi
> = core.serialization.object({
    amount: core.serialization.lazy(async () => (await import("..")).CreatePaymentLinkOfpiAmount),
    customer: core.serialization.string(),
    description: core.serialization.string(),
    allowedPaymentMethodTypes: core.serialization.property(
        "allowed_payment_method_types",
        core.serialization.list(
            core.serialization.lazy(async () => (await import("..")).EnumPaymentLinkAllowedPaymentMethod)
        )
    ),
    provider: core.serialization.lazy(async () => (await import("..")).EnumPaymentLinkProvider),
    paymentMethodDetails: core.serialization.property(
        "payment_method_details",
        core.serialization.lazyObject(async () => (await import("..")).PaymentMethodDetailsOfpi)
    ),
    callbackUrls: core.serialization.property(
        "callback_urls",
        core.serialization.lazyObject(async () => (await import("..")).PaymentLinkCallbackUrls).optional()
    ),
    expiresIn: core.serialization.property("expires_in", core.serialization.string().optional()),
});

export declare namespace CreatePaymentLinkOfpi {
    interface Raw {
        amount: serializers.CreatePaymentLinkOfpiAmount.Raw;
        customer: string;
        description: string;
        allowed_payment_method_types: serializers.EnumPaymentLinkAllowedPaymentMethod.Raw[];
        provider: serializers.EnumPaymentLinkProvider.Raw;
        payment_method_details: serializers.PaymentMethodDetailsOfpi.Raw;
        callback_urls?: serializers.PaymentLinkCallbackUrls.Raw | null;
        expires_in?: string | null;
    }
}
