/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as BelvoApi from "../../api";
import * as core from "../../core";

export const CreateBankAccountRequest: core.serialization.Schema<
    serializers.CreateBankAccountRequest.Raw,
    BelvoApi.CreateBankAccountRequest
> = core.serialization.undiscriminatedUnion([
    core.serialization.lazyObject(async () => (await import("..")).CreateBankAccountOfpi),
    core.serialization.lazyObject(async () => (await import("..")).CreateBankAccountPse),
]);

export declare namespace CreateBankAccountRequest {
    type Raw = serializers.CreateBankAccountOfpi.Raw | serializers.CreateBankAccountPse.Raw;
}
