/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as BelvoApi from "../../api";
import * as core from "../../core";

export const CreatePaymentIntentPseAmount: core.serialization.Schema<
    serializers.CreatePaymentIntentPseAmount.Raw,
    BelvoApi.CreatePaymentIntentPseAmount
> = core.serialization.undiscriminatedUnion([core.serialization.string(), core.serialization.number()]);

export declare namespace CreatePaymentIntentPseAmount {
    type Raw = string | number;
}
