/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Belvo from "../../api";
import * as core from "../../core";

export const CustomerPaginatedResponse: core.serialization.ObjectSchema<
    serializers.CustomerPaginatedResponse.Raw,
    Belvo.CustomerPaginatedResponse
> = core.serialization.object({
    count: core.serialization.number().optional(),
    next: core.serialization.string().optional(),
    previous: core.serialization.string().optional(),
    results: core.serialization
        .list(core.serialization.lazy(async () => (await import("..")).CustomerPaginatedResponseResultsItem))
        .optional(),
});

export declare namespace CustomerPaginatedResponse {
    interface Raw {
        count?: number | null;
        next?: string | null;
        previous?: string | null;
        results?: serializers.CustomerPaginatedResponseResultsItem.Raw[] | null;
    }
}
