/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Belvo from "../../api";
import * as core from "../../core";

export const DetailInvoiceResponse: core.serialization.Schema<
    serializers.DetailInvoiceResponse.Raw,
    Belvo.DetailInvoiceResponse
> = core.serialization.undiscriminatedUnion([
    core.serialization.lazyObject(async () => (await import("..")).InvoiceWithIdSat),
    core.serialization.lazyObject(async () => (await import("..")).InvoiceDian),
]);

export declare namespace DetailInvoiceResponse {
    type Raw = serializers.InvoiceWithIdSat.Raw | serializers.InvoiceDian.Raw;
}
