/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Belvo from "../../api";
import * as core from "../../core";

export const DetailTaxDeclarationResponse: core.serialization.Schema<
    serializers.DetailTaxDeclarationResponse.Raw,
    Belvo.DetailTaxDeclarationResponse
> = core.serialization.undiscriminatedUnion([
    core.serialization.lazyObject(async () => (await import("..")).TaxDeclarationIndividual),
    core.serialization.lazyObject(async () => (await import("..")).TaxDeclarationBusiness),
]);

export declare namespace DetailTaxDeclarationResponse {
    type Raw = serializers.TaxDeclarationIndividual.Raw | serializers.TaxDeclarationBusiness.Raw;
}
