/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Belvo from "../../api";
import * as core from "../../core";

export const DisplayCredentialsRequiredContentPse: core.serialization.ObjectSchema<
    serializers.DisplayCredentialsRequiredContentPse.Raw,
    Belvo.DisplayCredentialsRequiredContentPse
> = core.serialization.object({
    payerInstitution: core.serialization.property(
        "payer_institution",
        core.serialization.lazyObject(async () => (await import("..")).PaymentInstitution).optional()
    ),
});

export declare namespace DisplayCredentialsRequiredContentPse {
    interface Raw {
        payer_institution?: serializers.PaymentInstitution.Raw | null;
    }
}
