/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Belvo from "../../api";
import * as core from "../../core";

export const DocumentInformationIndividual: core.serialization.ObjectSchema<
    serializers.DocumentInformationIndividual.Raw,
    Belvo.DocumentInformationIndividual
> = core.serialization.object({
    name: core.serialization.string(),
    type: core.serialization.string(),
    formNumber: core.serialization.property("form_number", core.serialization.string()),
    year: core.serialization.number().optional(),
});

export declare namespace DocumentInformationIndividual {
    interface Raw {
        name: string;
        type: string;
        form_number: string;
        year?: number | null;
    }
}
