/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as BelvoApi from "../../api";
import * as core from "../../core";

export const DocumentIdBusiness: core.serialization.ObjectSchema<
    serializers.DocumentIdBusiness.Raw,
    BelvoApi.DocumentIdBusiness
> = core.serialization.object({
    documentType: core.serialization.property("document_type", core.serialization.string()),
    documentNumber: core.serialization.property("document_number", core.serialization.string()),
});

export declare namespace DocumentIdBusiness {
    interface Raw {
        document_type: string;
        document_number: string;
    }
}
