/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Belvo from "../../api";
import * as core from "../../core";

export const EnumPaymentsCurrency: core.serialization.Schema<
    serializers.EnumPaymentsCurrency.Raw,
    Belvo.EnumPaymentsCurrency
> = core.serialization.enum_(["BRL", "COP"]);

export declare namespace EnumPaymentsCurrency {
    type Raw = "BRL" | "COP";
}
