/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Belvo from "../../api";
import * as core from "../../core";

export const EnumIncomeVerificationAccountCategory: core.serialization.Schema<
    serializers.EnumIncomeVerificationAccountCategory.Raw,
    Belvo.EnumIncomeVerificationAccountCategory
> = core.serialization.enum_(["CHECKING_ACCOUNT", "SAVINGS_ACCOUNT"]);

export declare namespace EnumIncomeVerificationAccountCategory {
    type Raw = "CHECKING_ACCOUNT" | "SAVINGS_ACCOUNT";
}
