/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Belvo from "../../api";
import * as core from "../../core";

export const EnumPaymentLinksStatus: core.serialization.Schema<
    serializers.EnumPaymentLinksStatus.Raw,
    Belvo.EnumPaymentLinksStatus
> = core.serialization.enum_(["ACTIVE", "INACTIVE"]);

export declare namespace EnumPaymentLinksStatus {
    type Raw = "ACTIVE" | "INACTIVE";
}
