/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as BelvoApi from "../../api";
import * as core from "../../core";

export const EnumAccountCategory: core.serialization.Schema<
    serializers.EnumAccountCategory.Raw,
    BelvoApi.EnumAccountCategory
> = core.serialization.string().optional();

export declare namespace EnumAccountCategory {
    type Raw = string | null | undefined;
}
