/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Belvo from "../../api";
import * as core from "../../core";

export const EnumBankAccountHolderTypeOfpi: core.serialization.Schema<
    serializers.EnumBankAccountHolderTypeOfpi.Raw,
    Belvo.EnumBankAccountHolderTypeOfpi
> = core.serialization.enum_(["INDIVIDUAL", "BUSINESS"]);

export declare namespace EnumBankAccountHolderTypeOfpi {
    type Raw = "INDIVIDUAL" | "BUSINESS";
}
