/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Belvo from "../../api";
import * as core from "../../core";

export const EnumPaymentTransactionType: core.serialization.Schema<
    serializers.EnumPaymentTransactionType.Raw,
    Belvo.EnumPaymentTransactionType
> = core.serialization.enum_(["INFLOW", "OUTFLOW"]);

export declare namespace EnumPaymentTransactionType {
    type Raw = "INFLOW" | "OUTFLOW";
}
