/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as BelvoApi from "../../api";
import * as core from "../../core";

export const EnumCustomerIdentifierTypeOfpi: core.serialization.Schema<
    serializers.EnumCustomerIdentifierTypeOfpi.Raw,
    BelvoApi.EnumCustomerIdentifierTypeOfpi
> = core.serialization.enum_(["CPF", "CNPJ"]);

export declare namespace EnumCustomerIdentifierTypeOfpi {
    type Raw = "CPF" | "CNPJ";
}
