/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as BelvoApi from "../../api";
import * as core from "../../core";

export const EnumPaymentsCountry: core.serialization.Schema<
    serializers.EnumPaymentsCountry.Raw,
    BelvoApi.EnumPaymentsCountry
> = core.serialization.enum_(["BRA", "COL"]);

export declare namespace EnumPaymentsCountry {
    type Raw = "BRA" | "COL";
}
