/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Belvo from "../../api";
import * as core from "../../core";

export const EnumInvoiceSatPaymentMethod: core.serialization.Schema<
    serializers.EnumInvoiceSatPaymentMethod.Raw,
    Belvo.EnumInvoiceSatPaymentMethod
> = core.serialization.string().optional();

export declare namespace EnumInvoiceSatPaymentMethod {
    type Raw = string | null | undefined;
}
