/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Belvo from "../../api";
import * as core from "../../core";

export const EnumCustomerIdentifierTypePse: core.serialization.Schema<
    serializers.EnumCustomerIdentifierTypePse.Raw,
    Belvo.EnumCustomerIdentifierTypePse
> = core.serialization.enum_(["CC", "PP", "CE", "TI", "NIT"]);

export declare namespace EnumCustomerIdentifierTypePse {
    type Raw = "CC" | "PP" | "CE" | "TI" | "NIT";
}
