/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Belvo from "../../api";
import * as core from "../../core";

export const EnumIncomeMinimumConfidenceLevelRequest: core.serialization.Schema<
    serializers.EnumIncomeMinimumConfidenceLevelRequest.Raw,
    Belvo.EnumIncomeMinimumConfidenceLevelRequest
> = core.serialization.enum_(["HIGH", "MEDIUM", "LOW"]);

export declare namespace EnumIncomeMinimumConfidenceLevelRequest {
    type Raw = "HIGH" | "MEDIUM" | "LOW";
}
