/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Belvo from "../../api";
import * as core from "../../core";

export const EnumLinkAccessModeRequest: core.serialization.Schema<
    serializers.EnumLinkAccessModeRequest.Raw,
    Belvo.EnumLinkAccessModeRequest
> = core.serialization.enum_(["single", "recurrent"]);

export declare namespace EnumLinkAccessModeRequest {
    type Raw = "single" | "recurrent";
}
