/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as BelvoApi from "../../api";
import * as core from "../../core";

export const EnumTaxComplianceStatusOutcome: core.serialization.Schema<
    serializers.EnumTaxComplianceStatusOutcome.Raw,
    BelvoApi.EnumTaxComplianceStatusOutcome
> = core.serialization.enum_(["POSITIVE", "NEGATIVE", "NO_OBLIGATIONS"]);

export declare namespace EnumTaxComplianceStatusOutcome {
    type Raw = "POSITIVE" | "NEGATIVE" | "NO_OBLIGATIONS";
}
