/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as BelvoApi from "../../api";
import * as core from "../../core";

export const EnumCategorizationAccountCategory: core.serialization.Schema<
    serializers.EnumCategorizationAccountCategory.Raw,
    BelvoApi.EnumCategorizationAccountCategory
> = core.serialization.enum_(["CHECKING_ACCOUNT", "CREDIT_CARD", "LOAN_ACCOUNT", "SAVINGS_ACCOUNT"]);

export declare namespace EnumCategorizationAccountCategory {
    type Raw = "CHECKING_ACCOUNT" | "CREDIT_CARD" | "LOAN_ACCOUNT" | "SAVINGS_ACCOUNT";
}
