/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as BelvoApi from "../../api";
import * as core from "../../core";

export const EnumReceivableTransactionType: core.serialization.Schema<
    serializers.EnumReceivableTransactionType.Raw,
    BelvoApi.EnumReceivableTransactionType
> = core.serialization.string().optional();

export declare namespace EnumReceivableTransactionType {
    type Raw = string | null | undefined;
}
