/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Belvo from "../../api";
import * as core from "../../core";

export const EnumTaxRetentionPaymentStatus: core.serialization.Schema<
    serializers.EnumTaxRetentionPaymentStatus.Raw,
    Belvo.EnumTaxRetentionPaymentStatus
> = core.serialization.enum_(["PAID", "PROVISIONED"]);

export declare namespace EnumTaxRetentionPaymentStatus {
    type Raw = "PAID" | "PROVISIONED";
}
