/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Belvo from "../../api";
import * as core from "../../core";

export const EnumLinkStatus: core.serialization.Schema<serializers.EnumLinkStatus.Raw, Belvo.EnumLinkStatus> =
    core.serialization.enum_(["valid", "invalid", "unconfirmed", "token_required"]);

export declare namespace EnumLinkStatus {
    type Raw = "valid" | "invalid" | "unconfirmed" | "token_required";
}
