/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Belvo from "../../api";
import * as core from "../../core";

export const EnumCustomerType: core.serialization.Schema<serializers.EnumCustomerType.Raw, Belvo.EnumCustomerType> =
    core.serialization.enum_(["INDIVIDUAL", "BUSINESS"]);

export declare namespace EnumCustomerType {
    type Raw = "INDIVIDUAL" | "BUSINESS";
}
