/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as BelvoApi from "../../api";
import * as core from "../../core";

export const EnumIncomeVerificationAccountHolderType: core.serialization.Schema<
    serializers.EnumIncomeVerificationAccountHolderType.Raw,
    BelvoApi.EnumIncomeVerificationAccountHolderType
> = core.serialization.enum_(["INDIVIDUAL"]);

export declare namespace EnumIncomeVerificationAccountHolderType {
    type Raw = "INDIVIDUAL";
}
