/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as BelvoApi from "../../api";
import * as core from "../../core";

export const EnumTaxRetentionReceiverNationality: core.serialization.Schema<
    serializers.EnumTaxRetentionReceiverNationality.Raw,
    BelvoApi.EnumTaxRetentionReceiverNationality
> = core.serialization.enum_(["NATIONAL", "FOREIGN"]);

export declare namespace EnumTaxRetentionReceiverNationality {
    type Raw = "NATIONAL" | "FOREIGN";
}
