/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as BelvoApi from "../../api";
import * as core from "../../core";

export const EnumPaymentIntentStatus: core.serialization.Schema<
    serializers.EnumPaymentIntentStatus.Raw,
    BelvoApi.EnumPaymentIntentStatus
> = core.serialization.enum_(["REQUIRES_PAYMENT_METHOD", "REQUIRES_ACTION", "SUCCEEDED", "PROCESSING", "FAILED"]);

export declare namespace EnumPaymentIntentStatus {
    type Raw = "REQUIRES_PAYMENT_METHOD" | "REQUIRES_ACTION" | "SUCCEEDED" | "PROCESSING" | "FAILED";
}
