/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as BelvoApi from "../../api";
import * as core from "../../core";

export const EnumTransactionBillStatus: core.serialization.Schema<
    serializers.EnumTransactionBillStatus.Raw,
    BelvoApi.EnumTransactionBillStatus
> = core.serialization.string().optional();

export declare namespace EnumTransactionBillStatus {
    type Raw = string | null | undefined;
}
