/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as BelvoApi from "../../api";
import * as core from "../../core";

export const EnumInstitutionStatus: core.serialization.Schema<
    serializers.EnumInstitutionStatus.Raw,
    BelvoApi.EnumInstitutionStatus
> = core.serialization.enum_(["healthy", "down"]);

export declare namespace EnumInstitutionStatus {
    type Raw = "healthy" | "down";
}
