/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Belvo from "../../api";
import * as core from "../../core";

export const EnumRecurringExpenseCategory: core.serialization.Schema<
    serializers.EnumRecurringExpenseCategory.Raw,
    Belvo.EnumRecurringExpenseCategory
> = core.serialization.enum_([
    "Bills & Utilities",
    "Credits & Loans",
    "Insurance",
    "Online Platforms & Leisure",
    "Transport & Travel",
    "Taxes",
]);

export declare namespace EnumRecurringExpenseCategory {
    type Raw =
        | "Bills & Utilities"
        | "Credits & Loans"
        | "Insurance"
        | "Online Platforms & Leisure"
        | "Transport & Travel"
        | "Taxes";
}
