/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as BelvoApi from "../../api";
import * as core from "../../core";

export const EnumInstitutionType: core.serialization.Schema<
    serializers.EnumInstitutionType.Raw,
    BelvoApi.EnumInstitutionType
> = core.serialization.enum_(["bank", "fiscal", "employment"]);

export declare namespace EnumInstitutionType {
    type Raw = "bank" | "fiscal" | "employment";
}
