/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as BelvoApi from "../../api";
import * as core from "../../core";

export const EyodIncomeVerificationBodyRequest: core.serialization.ObjectSchema<
    serializers.EyodIncomeVerificationBodyRequest.Raw,
    BelvoApi.EyodIncomeVerificationBodyRequest
> = core.serialization.object({
    transactionId: core.serialization.property("transaction_id", core.serialization.string()),
    accountHolderType: core.serialization.property(
        "account_holder_type",
        core.serialization.lazy(async () => (await import("..")).EnumIncomeVerificationAccountHolderType)
    ),
    accountHolderId: core.serialization.property("account_holder_id", core.serialization.string()),
    accountId: core.serialization.property("account_id", core.serialization.string()),
    accountCategory: core.serialization.property(
        "account_category",
        core.serialization.lazy(async () => (await import("..")).EnumIncomeVerificationAccountCategory)
    ),
    valueDate: core.serialization.property("value_date", core.serialization.string()),
    description: core.serialization.string(),
    type: core.serialization.lazy(async () => (await import("..")).EnumIncomeVerificationType),
    amount: core.serialization.number(),
    currency: core.serialization.string(),
    institution: core.serialization.string(),
});

export declare namespace EyodIncomeVerificationBodyRequest {
    interface Raw {
        transaction_id: string;
        account_holder_type: serializers.EnumIncomeVerificationAccountHolderType.Raw;
        account_holder_id: string;
        account_id: string;
        account_category: serializers.EnumIncomeVerificationAccountCategory.Raw;
        value_date: string;
        description: string;
        type: serializers.EnumIncomeVerificationType.Raw;
        amount: number;
        currency: string;
        institution: string;
    }
}
