/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as BelvoApi from "../../api";
import * as core from "../../core";

export const HolderBankAccountPse: core.serialization.ObjectSchema<
    serializers.HolderBankAccountPse.Raw,
    BelvoApi.HolderBankAccountPse
> = core.serialization.object({
    type: core.serialization.lazy(async () => (await import("..")).EnumPaymentIntentHolderTypePse).optional(),
    information: core.serialization
        .lazyObject(async () => (await import("..")).HolderBankAccountInformationPse)
        .optional(),
});

export declare namespace HolderBankAccountPse {
    interface Raw {
        type?: serializers.EnumPaymentIntentHolderTypePse.Raw | null;
        information?: serializers.HolderBankAccountInformationPse.Raw | null;
    }
}
