/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Belvo from "../../api";
import * as core from "../../core";

export const HolderInformationBusinessPseResponse: core.serialization.ObjectSchema<
    serializers.HolderInformationBusinessPseResponse.Raw,
    Belvo.HolderInformationBusinessPseResponse
> = core.serialization.object({
    name: core.serialization.string(),
});

export declare namespace HolderInformationBusinessPseResponse {
    interface Raw {
        name: string;
    }
}
