/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as BelvoApi from "../../api";
import * as core from "../../core";

export const HolderInformationBusinessOfpi: core.serialization.ObjectSchema<
    serializers.HolderInformationBusinessOfpi.Raw,
    BelvoApi.HolderInformationBusinessOfpi
> = core.serialization.object({
    name: core.serialization.string(),
    identifierType: core.serialization.property(
        "identifier_type",
        core.serialization.lazy(async () => (await import("..")).EnumCustomerIdentifierTypeOfpi)
    ),
    identifier: core.serialization.string(),
});

export declare namespace HolderInformationBusinessOfpi {
    interface Raw {
        name: string;
        identifier_type: serializers.EnumCustomerIdentifierTypeOfpi.Raw;
        identifier: string;
    }
}
