/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as BelvoApi from "../../api";
import * as core from "../../core";

export const InstitutionsFeature: core.serialization.ObjectSchema<
    serializers.InstitutionsFeature.Raw,
    BelvoApi.InstitutionsFeature
> = core.serialization.object({
    name: core.serialization.string().optional(),
    description: core.serialization.string().optional(),
});

export declare namespace InstitutionsFeature {
    interface Raw {
        name?: string | null;
        description?: string | null;
    }
}
