/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as BelvoApi from "../../api";
import * as core from "../../core";

export const InstitutionsFormFieldValues: core.serialization.ObjectSchema<
    serializers.InstitutionsFormFieldValues.Raw,
    BelvoApi.InstitutionsFormFieldValues
> = core.serialization.object({
    code: core.serialization.string().optional(),
    label: core.serialization.string().optional(),
    validation: core.serialization.string().optional(),
    validationMessage: core.serialization.property("validation_message", core.serialization.string().optional()),
    placeholder: core.serialization.string().optional(),
});

export declare namespace InstitutionsFormFieldValues {
    interface Raw {
        code?: string | null;
        label?: string | null;
        validation?: string | null;
        validation_message?: string | null;
        placeholder?: string | null;
    }
}
