/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Belvo from "../../api";
import * as core from "../../core";

export const LastErrorLoginError: core.serialization.ObjectSchema<
    serializers.LastErrorLoginError.Raw,
    Belvo.LastErrorLoginError
> = core.serialization.object({
    errorCode: core.serialization.property("error_code", core.serialization.string()),
    errorMessage: core.serialization.property("error_message", core.serialization.string()),
});

export declare namespace LastErrorLoginError {
    interface Raw {
        error_code: string;
        error_message: string;
    }
}
