/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as BelvoApi from "../../api";
import * as core from "../../core";

export const NextStepDisplayConfirmationRequiredOfpi: core.serialization.ObjectSchema<
    serializers.NextStepDisplayConfirmationRequiredOfpi.Raw,
    BelvoApi.NextStepDisplayConfirmationRequiredOfpi
> = core.serialization.object({
    type: core.serialization
        .lazy(async () => (await import("..")).NextStepDisplayConfirmationRequiredOfpiType)
        .optional(),
    openFinanceDisplayConfirmationRequired: core.serialization.property(
        "open_finance_display_confirmation_required",
        core.serialization.lazyObject(async () => (await import("..")).DisplayConfirmationRequiredOfpi).optional()
    ),
    readyToConfirm: core.serialization.property("ready_to_confirm", core.serialization.boolean().optional()),
});

export declare namespace NextStepDisplayConfirmationRequiredOfpi {
    interface Raw {
        type?: serializers.NextStepDisplayConfirmationRequiredOfpiType.Raw | null;
        open_finance_display_confirmation_required?: serializers.DisplayConfirmationRequiredOfpi.Raw | null;
        ready_to_confirm?: boolean | null;
    }
}
