/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Belvo from "../../api";
import * as core from "../../core";

export const NextStepDisplayPaymentFailed: core.serialization.ObjectSchema<
    serializers.NextStepDisplayPaymentFailed.Raw,
    Belvo.NextStepDisplayPaymentFailed
> = core.serialization.object({
    type: core.serialization.lazy(async () => (await import("..")).NextStepDisplayPaymentFailedType).optional(),
    openFinanceDisplayPaymentFailed: core.serialization.property(
        "open_finance_display_payment_failed",
        core.serialization.lazyObject(async () => (await import("..")).DisplayPaymentFailed).optional()
    ),
    readyToConfirm: core.serialization.property("ready_to_confirm", core.serialization.boolean().optional()),
});

export declare namespace NextStepDisplayPaymentFailed {
    interface Raw {
        type?: serializers.NextStepDisplayPaymentFailedType.Raw | null;
        open_finance_display_payment_failed?: serializers.DisplayPaymentFailed.Raw | null;
        ready_to_confirm?: boolean | null;
    }
}
