/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Belvo from "../../api";
import * as core from "../../core";

export const Owner: core.serialization.ObjectSchema<serializers.Owner.Raw, Belvo.Owner> = core.serialization.object({
    id: core.serialization.string().optional(),
    link: core.serialization.string().optional(),
    internalIdentification: core.serialization.property(
        "internal_identification",
        core.serialization.string().optional()
    ),
    collectedAt: core.serialization.property("collected_at", core.serialization.string().optional()),
    createdAt: core.serialization.property("created_at", core.serialization.string().optional()),
    displayName: core.serialization.property("display_name", core.serialization.string().optional()),
    email: core.serialization.string().optional(),
    phoneNumber: core.serialization.property("phone_number", core.serialization.string().optional()),
    address: core.serialization.string().optional(),
    documentId: core.serialization.property(
        "document_id",
        core.serialization.lazyObject(async () => (await import("..")).OwnerDocumentId).optional()
    ),
    firstName: core.serialization.property("first_name", core.serialization.string().optional()),
    lastName: core.serialization.property("last_name", core.serialization.string().optional()),
    secondLastName: core.serialization.property("second_last_name", core.serialization.string().optional()),
});

export declare namespace Owner {
    interface Raw {
        id?: string | null;
        link?: string | null;
        internal_identification?: string | null;
        collected_at?: string | null;
        created_at?: string | null;
        display_name?: string | null;
        email?: string | null;
        phone_number?: string | null;
        address?: string | null;
        document_id?: serializers.OwnerDocumentId.Raw | null;
        first_name?: string | null;
        last_name?: string | null;
        second_last_name?: string | null;
    }
}
