/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Belvo from "../../api";
import * as core from "../../core";

export const PatchBodyWithoutSaveData: core.serialization.ObjectSchema<
    serializers.PatchBodyWithoutSaveData.Raw,
    Belvo.PatchBodyWithoutSaveData
> = core.serialization.object({
    session: core.serialization.string(),
    token: core.serialization.string().optional(),
    link: core.serialization.string(),
});

export declare namespace PatchBodyWithoutSaveData {
    interface Raw {
        session: string;
        token?: string | null;
        link: string;
    }
}
