/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Belvo from "../../api";
import * as core from "../../core";

export const PaymentIntentsPaymentMethodDetailsBodyPse: core.serialization.ObjectSchema<
    serializers.PaymentIntentsPaymentMethodDetailsBodyPse.Raw,
    Belvo.PaymentIntentsPaymentMethodDetailsBodyPse
> = core.serialization.object({
    beneficiaryBankAccount: core.serialization.property("beneficiary_bank_account", core.serialization.string()),
    callbackUrl: core.serialization.property("callback_url", core.serialization.string().optional()),
    belvoFlow: core.serialization.property("belvo_flow", core.serialization.boolean()),
});

export declare namespace PaymentIntentsPaymentMethodDetailsBodyPse {
    interface Raw {
        beneficiary_bank_account: string;
        callback_url?: string | null;
        belvo_flow: boolean;
    }
}
