/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Belvo from "../../api";
import * as core from "../../core";

export const PaymentMethodInformationPse: core.serialization.ObjectSchema<
    serializers.PaymentMethodInformationPse.Raw,
    Belvo.PaymentMethodInformationPse
> = core.serialization.object({
    pse: core.serialization.lazyObject(async () => (await import("..")).PaymentMethodInformationBodyPse).optional(),
});

export declare namespace PaymentMethodInformationPse {
    interface Raw {
        pse?: serializers.PaymentMethodInformationBodyPse.Raw | null;
    }
}
