/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as BelvoApi from "../../api";
import * as core from "../../core";

export const PaymentMethodInformationOfpi: core.serialization.ObjectSchema<
    serializers.PaymentMethodInformationOfpi.Raw,
    BelvoApi.PaymentMethodInformationOfpi
> = core.serialization.object({
    openFinance: core.serialization.property(
        "open_finance",
        core.serialization.lazyObject(async () => (await import("..")).PaymentMethodInformationBodyOfpi).optional()
    ),
});

export declare namespace PaymentMethodInformationOfpi {
    interface Raw {
        open_finance?: serializers.PaymentMethodInformationBodyOfpi.Raw | null;
    }
}
