/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as BelvoApi from "../../api";
import * as core from "../../core";

export const PaymentIntentPaymentMethodDetailsBodyIndividualOfpi: core.serialization.ObjectSchema<
    serializers.PaymentIntentPaymentMethodDetailsBodyIndividualOfpi.Raw,
    BelvoApi.PaymentIntentPaymentMethodDetailsBodyIndividualOfpi
> = core.serialization.object({
    beneficiaryBankAccount: core.serialization.property("beneficiary_bank_account", core.serialization.string()),
    payerInstitution: core.serialization.property("payer_institution", core.serialization.string()),
    callbackUrl: core.serialization.property("callback_url", core.serialization.string()),
    cpf: core.serialization.string().optional(),
});

export declare namespace PaymentIntentPaymentMethodDetailsBodyIndividualOfpi {
    interface Raw {
        beneficiary_bank_account: string;
        payer_institution: string;
        callback_url: string;
        cpf?: string | null;
    }
}
