/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Belvo from "../../api";
import * as core from "../../core";

export const PaymentLinkCallbackUrls: core.serialization.ObjectSchema<
    serializers.PaymentLinkCallbackUrls.Raw,
    Belvo.PaymentLinkCallbackUrls
> = core.serialization.object({
    cancel: core.serialization.string().optional(),
    success: core.serialization.string().optional(),
});

export declare namespace PaymentLinkCallbackUrls {
    interface Raw {
        cancel?: string | null;
        success?: string | null;
    }
}
