/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as BelvoApi from "../../api";
import * as core from "../../core";

export const PaymentMethodDetailsPse: core.serialization.ObjectSchema<
    serializers.PaymentMethodDetailsPse.Raw,
    BelvoApi.PaymentMethodDetailsPse
> = core.serialization.object({
    pse: core.serialization.lazyObject(async () => (await import("..")).PaymentLinksPaymentMethodDetailsBodyPse),
});

export declare namespace PaymentMethodDetailsPse {
    interface Raw {
        pse: serializers.PaymentLinksPaymentMethodDetailsBodyPse.Raw;
    }
}
