/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as BelvoApi from "../../api";
import * as core from "../../core";

export const PaymentsWay: core.serialization.ObjectSchema<serializers.PaymentsWay.Raw, BelvoApi.PaymentsWay> =
    core.serialization.object({
        terminalId: core.serialization.property("terminal_id", core.serialization.number()),
        formId: core.serialization.property("form_id", core.serialization.number()),
    });

export declare namespace PaymentsWay {
    interface Raw {
        terminal_id: number;
        form_id: number;
    }
}
