/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Belvo from "../../api";
import * as core from "../../core";

export const PaymentIntentPaymentMethodDetailsPse: core.serialization.ObjectSchema<
    serializers.PaymentIntentPaymentMethodDetailsPse.Raw,
    Belvo.PaymentIntentPaymentMethodDetailsPse
> = core.serialization.object({
    pse: core.serialization
        .lazyObject(async () => (await import("..")).PaymentIntentPaymentMethodDetailsBodyPse)
        .optional(),
});

export declare namespace PaymentIntentPaymentMethodDetailsPse {
    interface Raw {
        pse?: serializers.PaymentIntentPaymentMethodDetailsBodyPse.Raw | null;
    }
}
