/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as BelvoApi from "../../api";
import * as core from "../../core";

export const ProvidersPse: core.serialization.ObjectSchema<serializers.ProvidersPse.Raw, BelvoApi.ProvidersPse> =
    core.serialization.object({
        paymentsWay: core.serialization.property(
            "payments_way",
            core.serialization.lazyObject(async () => (await import("..")).PaymentsWay).optional()
        ),
    });

export declare namespace ProvidersPse {
    interface Raw {
        payments_way?: serializers.PaymentsWay.Raw | null;
    }
}
