/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Belvo from "../../api";
import * as core from "../../core";

export const RecevablesTransactionFees: core.serialization.ObjectSchema<
    serializers.RecevablesTransactionFees.Raw,
    Belvo.RecevablesTransactionFees
> = core.serialization.object({
    type: core.serialization.lazy(async () => (await import("..")).EnumReceivableTransactionFeeType),
    value: core.serialization.number(),
});

export declare namespace RecevablesTransactionFees {
    interface Raw {
        type: serializers.EnumReceivableTransactionFeeType.Raw;
        value: number;
    }
}
