/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as BelvoApi from "../../api";
import * as core from "../../core";

export const RetrieveTaxReturnsResponseItem: core.serialization.Schema<
    serializers.RetrieveTaxReturnsResponseItem.Raw,
    BelvoApi.RetrieveTaxReturnsResponseItem
> = core.serialization.undiscriminatedUnion([
    core.serialization.lazy(async () => (await import("..")).TaxReturnPersonal),
    core.serialization.lazy(async () => (await import("..")).TaxReturnPersonalMonthly),
    core.serialization.lazy(async () => (await import("..")).TaxReturnBusiness),
    core.serialization.lazy(async () => (await import("..")).TaxReturnBusinessMonthly),
]);

export declare namespace RetrieveTaxReturnsResponseItem {
    type Raw =
        | serializers.TaxReturnPersonal.Raw
        | serializers.TaxReturnPersonalMonthly.Raw
        | serializers.TaxReturnBusiness.Raw
        | serializers.TaxReturnBusinessMonthly.Raw;
}
