/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Belvo from "../../api";
import * as core from "../../core";

export const RiskInsightsLoansMetrics: core.serialization.ObjectSchema<
    serializers.RiskInsightsLoansMetrics.Raw,
    Belvo.RiskInsightsLoansMetrics
> = core.serialization.object({
    numAccounts: core.serialization.property("num_accounts", core.serialization.number()),
    sumLoansPrincipal: core.serialization.property("sum_loans_principal", core.serialization.number().optional()),
    sumLoansOutstandingPrincipal: core.serialization.property(
        "sum_loans_outstanding_principal",
        core.serialization.number().optional()
    ),
    sumLoansMonthlyPayment: core.serialization.property(
        "sum_loans_monthly_payment",
        core.serialization.number().optional()
    ),
});

export declare namespace RiskInsightsLoansMetrics {
    interface Raw {
        num_accounts: number;
        sum_loans_principal?: number | null;
        sum_loans_outstanding_principal?: number | null;
        sum_loans_monthly_payment?: number | null;
    }
}
