/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as BelvoApi from "../../api";
import * as core from "../../core";

export const RiskInsightsTransactionMetrics: core.serialization.ObjectSchema<
    serializers.RiskInsightsTransactionMetrics.Raw,
    BelvoApi.RiskInsightsTransactionMetrics
> = core.serialization.object({
    numTransactions1W: core.serialization.property("num_transactions_1w", core.serialization.number()),
    numTransactions1M: core.serialization.property("num_transactions_1m", core.serialization.number()),
    numTransactions3M: core.serialization.property("num_transactions_3m", core.serialization.number()),
    numIncomingTransactions1W: core.serialization.property("num_incoming_transactions_1w", core.serialization.number()),
    numIncomingTransactions1M: core.serialization.property("num_incoming_transactions_1m", core.serialization.number()),
    numIncomingTransactions3M: core.serialization.property("num_incoming_transactions_3m", core.serialization.number()),
    numOutgoingTransactions1W: core.serialization.property("num_outgoing_transactions_1w", core.serialization.number()),
    numOutgoingTransactions1M: core.serialization.property("num_outgoing_transactions_1m", core.serialization.number()),
    numOutgoingTransactions3M: core.serialization.property("num_outgoing_transactions_3m", core.serialization.number()),
    sumIncomingAmount1W: core.serialization.property("sum_incoming_amount_1w", core.serialization.number().optional()),
    sumIncomingAmount1M: core.serialization.property("sum_incoming_amount_1m", core.serialization.number().optional()),
    sumIncomingAmount3M: core.serialization.property("sum_incoming_amount_3m", core.serialization.number().optional()),
    sumOutgoingAmount1W: core.serialization.property("sum_outgoing_amount_1w", core.serialization.number().optional()),
    sumOutgoingAmount1M: core.serialization.property("sum_outgoing_amount_1m", core.serialization.number().optional()),
    sumOutgoingAmount3M: core.serialization.property("sum_outgoing_amount_3m", core.serialization.number().optional()),
    maxIncomingAmount1W: core.serialization.property("max_incoming_amount_1w", core.serialization.number().optional()),
    maxIncomingAmount1M: core.serialization.property("max_incoming_amount_1m", core.serialization.number().optional()),
    maxIncomingAmount3M: core.serialization.property("max_incoming_amount_3m", core.serialization.number().optional()),
    maxOutgoingAmount1W: core.serialization.property("max_outgoing_amount_1w", core.serialization.number().optional()),
    maxOutgoingAmount1M: core.serialization.property("max_outgoing_amount_1m", core.serialization.number().optional()),
    maxOutgoingAmount3M: core.serialization.property("max_outgoing_amount_3m", core.serialization.number().optional()),
    meanIncomingAmount1W: core.serialization.property(
        "mean_incoming_amount_1w",
        core.serialization.number().optional()
    ),
    meanIncomingAmount1M: core.serialization.property(
        "mean_incoming_amount_1m",
        core.serialization.number().optional()
    ),
    meanIncomingAmount3M: core.serialization.property(
        "mean_incoming_amount_3m",
        core.serialization.number().optional()
    ),
    meanOutgoingAmount1W: core.serialization.property(
        "mean_outgoing_amount_1w",
        core.serialization.number().optional()
    ),
    meanOutgoingAmount1M: core.serialization.property(
        "mean_outgoing_amount_1m",
        core.serialization.number().optional()
    ),
    meanOutgoingAmount3M: core.serialization.property(
        "mean_outgoing_amount_3m",
        core.serialization.number().optional()
    ),
});

export declare namespace RiskInsightsTransactionMetrics {
    interface Raw {
        num_transactions_1w: number;
        num_transactions_1m: number;
        num_transactions_3m: number;
        num_incoming_transactions_1w: number;
        num_incoming_transactions_1m: number;
        num_incoming_transactions_3m: number;
        num_outgoing_transactions_1w: number;
        num_outgoing_transactions_1m: number;
        num_outgoing_transactions_3m: number;
        sum_incoming_amount_1w?: number | null;
        sum_incoming_amount_1m?: number | null;
        sum_incoming_amount_3m?: number | null;
        sum_outgoing_amount_1w?: number | null;
        sum_outgoing_amount_1m?: number | null;
        sum_outgoing_amount_3m?: number | null;
        max_incoming_amount_1w?: number | null;
        max_incoming_amount_1m?: number | null;
        max_incoming_amount_3m?: number | null;
        max_outgoing_amount_1w?: number | null;
        max_outgoing_amount_1m?: number | null;
        max_outgoing_amount_3m?: number | null;
        mean_incoming_amount_1w?: number | null;
        mean_incoming_amount_1m?: number | null;
        mean_incoming_amount_3m?: number | null;
        mean_outgoing_amount_1w?: number | null;
        mean_outgoing_amount_1m?: number | null;
        mean_outgoing_amount_3m?: number | null;
    }
}
