/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as BelvoApi from "../../api";
import * as core from "../../core";

export const SecretKeys: core.serialization.ObjectSchema<serializers.SecretKeys.Raw, BelvoApi.SecretKeys> =
    core.serialization.object({
        id: core.serialization.string(),
        password: core.serialization.string(),
        createdAt: core.serialization.property("created_at", core.serialization.string()),
        lastUsed: core.serialization.property("last_used", core.serialization.string()),
    });

export declare namespace SecretKeys {
    interface Raw {
        id: string;
        password: string;
        created_at: string;
        last_used: string;
    }
}
