/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as BelvoApi from "../../api";
import * as core from "../../core";

export const TaxReturnsMonthlyRequest: core.serialization.ObjectSchema<
    serializers.TaxReturnsMonthlyRequest.Raw,
    BelvoApi.TaxReturnsMonthlyRequest
> = core.serialization.object({
    link: core.serialization.string(),
    attachPdf: core.serialization.property("attach_pdf", core.serialization.boolean().optional()),
    saveData: core.serialization.property("save_data", core.serialization.boolean().optional()),
    type: core.serialization.string(),
    dateFrom: core.serialization.property("date_from", core.serialization.string()),
    dateTo: core.serialization.property("date_to", core.serialization.string()),
});

export declare namespace TaxReturnsMonthlyRequest {
    interface Raw {
        link: string;
        attach_pdf?: boolean | null;
        save_data?: boolean | null;
        type: string;
        date_from: string;
        date_to: string;
    }
}
