/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Belvo from "../../api";
import * as core from "../../core";

export const TransactionBankAccountOfpi: core.serialization.Schema<
    serializers.TransactionBankAccountOfpi.Raw,
    Belvo.TransactionBankAccountOfpi
> = core.serialization.record(core.serialization.string(), core.serialization.unknown());

export declare namespace TransactionBankAccountOfpi {
    type Raw = Record<string, unknown>;
}
