/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BelvoApi from "../../../..";

export interface ListPaymentLinksRequest {
    page?: number;
    pageSize?: number;
    createdAt?: string;
    createdAtGt?: string;
    createdAtGte?: string;
    createdAtLt?: string;
    createdAtLte?: string;
    createdAtRange?: string;
    status?: BelvoApi.ListPaymentLinksRequestStatus;
    ordering?: BelvoApi.ListPaymentLinksRequestOrdering;
    search?: string;
}
