/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as BelvoApi from "../../../../api";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<
    serializers.invoices.retrieveInvoices.Response.Raw,
    BelvoApi.RetrieveInvoicesResponseItem[]
> = core.serialization.list(
    core.serialization.lazy(async () => (await import("../../..")).RetrieveInvoicesResponseItem)
);

export declare namespace Response {
    type Raw = serializers.RetrieveInvoicesResponseItem.Raw[];
}
