/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Belvo from "../../../../api";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<
    serializers.taxDeclarations.retrieveTaxDeclarations.Response.Raw,
    Belvo.RetrieveTaxDeclarationsResponseItem[]
> = core.serialization.list(
    core.serialization.lazy(async () => (await import("../../..")).RetrieveTaxDeclarationsResponseItem)
);

export declare namespace Response {
    type Raw = serializers.RetrieveTaxDeclarationsResponseItem.Raw[];
}
