/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as Belvo from "../../../../../api";
import * as core from "../../../../../core";

export const ChangeAccessMode: core.serialization.Schema<
    serializers.ChangeAccessMode.Raw,
    Omit<Belvo.ChangeAccessMode, "omit" | "fields">
> = core.serialization.object({
    accessMode: core.serialization.property(
        "access_mode",
        core.serialization.lazy(async () => (await import("../../../..")).EnumLinkAccessModeRequest)
    ),
});

export declare namespace ChangeAccessMode {
    interface Raw {
        access_mode: serializers.EnumLinkAccessModeRequest.Raw;
    }
}
